"""add chunk embeddings

Revision ID: 6bf6daefbe6d
Revises: 21e22f2c2d0c
Create Date: 2026-10-06 22:59:06.420170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '6bf6daefbe6d'
down_revision: Union[str, Sequence[str], None] = '21e22f2c2d0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    op.add_column('chunks', sa.Column('embedding_model', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'embedding_model')
    op.drop_column('chunks', 'embedding')
    # ### end Alembic commands ###
